/**
 * Extracts plain text from public/resume.pdf and writes it to
 * src/data/resumeText.ts so the chat widget can use it at runtime
 * without a fragile browser-side PDF fetch/parse step.
 *
 * Run manually after updating the PDF:
 *   node scripts/extract-resume.mjs
 */

import { getDocument, GlobalWorkerOptions } from "pdfjs-dist/legacy/build/pdf.mjs";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { resolve, dirname } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const workerPath = resolve(root, "node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs");
GlobalWorkerOptions.workerSrc = workerPath;

const pdfPath = resolve(root, "public/resume.pdf");
if (!existsSync(pdfPath)) {
  console.error("public/resume.pdf not found — skipping extraction.");
  process.exit(0);
}

const data = readFileSync(pdfPath);
const pdf = await getDocument({ data: data.buffer, useSystemFonts: true }).promise;

let raw = "";
for (let i = 1; i <= pdf.numPages; i++) {
  const page = await pdf.getPage(i);
  const content = await page.getTextContent();
  raw += content.items.map((item) => item.str).join(" ") + "\n";
}

// Some PDFs encode text with a space between every character (e.g. "y u a n").
// Collapse sequences of 3+ single chars/digits/symbols separated by spaces.
let text = raw;
for (let pass = 0; pass < 5; pass++) {
  text = text.replace(/(^|[\s])([A-Za-z0-9@._()+\-]) ([A-Za-z0-9@._()+\-]) ([A-Za-z0-9@._()+\-])/g,
    (_, pre, a, b, c) => `${pre}${a}${b}${c}`);
}
// Clean up leftover double-spaces
text = text.replace(/ {2,}/g, " ").trim();

const output = `// Auto-generated by scripts/extract-resume.mjs — run this script after updating public/resume.pdf
const resumeText = ${JSON.stringify(text)};
export default resumeText;
`;

const outPath = resolve(root, "src/data/resumeText.ts");
writeFileSync(outPath, output, "utf8");
console.log(`Done. Extracted ${text.length} characters from ${pdf.numPages} page(s) → src/data/resumeText.ts`);
